# Ceneral Configuration File

language: "en"

modules:
  # Rcon manager. Allows sending RCON commands to other servers
  rcon-manager: true
  # Rcon server. Enables Velocity RCON server to run
  rcon-server: true
  # PHP Runner. Allows you to download the PHP script
  php-runner: true
  # BASH Runner. Allows you to download the BASH script
  bash-runner: true